### ISSUE TITLE
Any Code Review?

### ISSUE THREAD

**Issue by changkun** [MIMUC-MMN/assignments-16-17#9]
I open this issue due to code review helps beginner write better and elegant code. If this repo has no review procedure, how do we find out our code quality?

**Comment by TobiasSeitz** [comment]
We review all code that is submitted through UniWorX. If we then have time, we browse through the code here and correct it where necessary. 

This repo, however, is mostly meant to see how others solved the same problem and which other approaches exist (which is also part of the learning process).

**Comment by changkun** [comment]
Thanks for the explanation of this repo, I'll keep learning from this repo.
